### ISSUE TITLE
Failed to fetch plugin

### ISSUE THREAD

**Issue by jorgemejia** [protonet/cordova-plugin-image-resizer#64]
I'm trying to install this plugin but I have the next issue:

Failed to fetch plugin https://github.com/protonet/cordova-plugin-image-resizer.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

This is my enviroment:

Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : no whitelisted plugins (15 plugins total)

System:

   NodeJS : v8.11.1 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS

**Comment by miqmago** [comment]
This is a great plugin and was perfectly working, but this error is very frustrating... The id change is a mess and has made this plugin totally unusable... Any solution on how to proceed to repair? I've tried to remove any reference to the plugin anywhere in the project but still cannot install

**Comment by miqmago** [comment]
Finally I've searched `protonet` and removing everything relate. I had to remove also the files from android platform as having this error:

```
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-simple-image-resizer': CordovaError: Uh oh!
"/Volumes/Apps/MyApp/app/platforms/android/src/info/protonet/imageresizer/ImageResizer.java" already exists!
    at copyNewFile (/Volumes/Apps/MyApp/app/platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/Volumes/Apps/MyApp/app/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Volumes/Apps/MyApp/app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Volumes/Apps/MyApp/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Volumes/Apps/MyApp/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Volumes/Apps/MyApp/app/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/Volumes/Apps/MyApp/app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Volumes/Apps/MyApp/app/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Volumes/Apps/MyApp/app/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Volumes/Apps/MyApp/app/platforms/android/cordova/node_modules/q/q.js:570:49
```

Finally I could do...

**Comment by mateuszroth** [comment]
You can try with `cordova plugin add https://github.com/JoschkaSchulz/cordova-plugin-image-resizer.git`, the command from the README file is incorrect.

**Comment by thfontaine** [comment]
Even with `
cordova plugin add https://github.com/JoschkaSchulz/cordova-plugin-image-resizer.git`, I have the same issue :

```
Failed to fetch plugin https://github.com/JoschkaSchulz/cordova-plugin-image-resizer.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/JoschkaSchulz/cordova-plugin-image-resizer.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/JoschkaSchulz/cordova-plugin-image-resizer.git/': Problem with the SSL CA cert (path? access rights?)
```

Env: 
```
cli packages: (/path/to/app/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 

local packages:

    @ionic/app-scripts : 2.0.0
    Cordova Platforms  : android 7.1.0 browser 5.0.4
    Ionic Framework    : ionic-angular 3.5.0

System:

    Node : v10.14.1
    npm  : 5.10.0 
    OS   : Linux 4.10
```

**Comment by r-guerin** [comment]
Having the same issue, even with the corrected URL. Did anyone find a workaround ?
