### ISSUE TITLE
Plugin crash the app when trying to resize an image from file (i.e. gallery)

### ISSUE THREAD

**Issue by eliaweiss** [protonet/cordova-plugin-image-resizer#8]
code:

```
window.imageResizer.resizeImage(
               function(data) { 
                    console.log("resizeImage : \r\n" + data);
                }
               , function (error) {
                 console.log("Error : \r\n" + error);
               }, imageURI, 750, 750, {
                  resizeType: ImageResizer.RESIZE_TYPE_PIXEL,
                  imageDataType: ImageResizer.IMAGE_DATA_TYPE_URL,
                  format: ImageResizer.FORMAT_JPG
               }
            );
```

If you imageURI is an image chosen from gallery "content://media/external/images/media/5045"

the plugin crashes the app.

More info:
cordova -v 6.1.0
cordova platform version android 5.1.1
cordova-plugin-image-resizer 1.0.0 "ImageResizer"
android version 4 - 5

code for getting the image from the device:

```
navigator.camera.getPicture(
  that.photoTaken,
  that.onCaptureFail, {
    destinationType: Camera.DestinationType.FILE_URI,
    sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
    mediaType: Camera.MediaType.PICTURE,
    saveToPhotoAlbum: true
  }
);
```

**Comment by twainyoung** [comment]
i met the same issue recently, which is wired , if i get image from camera ,the" resizeImage"  function works fine , if i choose image from  PHOTOLIBRARY,  app crash.

**Comment by srameshr** [comment]
Same here. Damn it. It works fine on IOS but not on Android!  Here are the crash logs.

```
E/AndroidRuntime( 4183): FATAL EXCEPTION: pool-1-thread-2
E/AndroidRuntime( 4183): Process: com.myapp.android, PID: 4183
E/AndroidRuntime( 4183): java.lang.IllegalArgumentException: Found query in URI: file:///storage/emulated/0/Android/data/com.myapp.android/cache/IMG_20161120_204314.jpg?1479654794267
E/AndroidRuntime( 4183):    at java.io.File.checkURI(File.java:235)
E/AndroidRuntime( 4183):    at java.io.File.<init>(File.java:177)
E/AndroidRuntime( 4183):    at com.raananw.ImageResizePlugin$ImageTools.getBitmap(ImageResizePlugin.java:102)
E/AndroidRuntime( 4183):    at com.raananw.ImageResizePlugin$ResizeImage.run(ImageResizePlugin.java:197)
E/AndroidRuntime( 4183):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 4183):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 4183):    at java.lang.Thread.run(Thread.java:841)
E/Sensors (  822): Lightsensor values:49.000000
E/android.os.Debug(  822): !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error
E/Sensors (  822): Lightsensor values:49.000000
E/libEGL  ( 4183): call to OpenGL ES API with no current context (logged once per thread)
```

Will this ever be resolved, seeing that there is no activity on the repo. :(

**Comment by JoschkaSchulz** [comment]
I get all the new messages but haven't enough time to fix the stuff... if someone would like to write a bugfix and creates a pull request I will check and merge it.

**Comment by srameshr** [comment]
@JoschkaSchulz I have no idea about objective c or java. Could you please fix this?  Lots of people are dependent on this.

**Comment by salzig** [comment]
@srameshr 
```
Found query in URI: file:///storage/emulated/0/Android/data/com.myapp.android/cache/IMG_20161120_204314.jpg?1479654794267
```
maybe call it without query string then?

btw, maybe i'm wrong, but you're not using the plugin provided by this repository (`com.raananw.ImageResizePlugin` vs. `info.protonet.imageresizer.ImageResizer`). Maybe you should call the author of `com.raananw.ImageResizePlugin` for action.

**Comment by srameshr** [comment]
Both these repositories are similar. I have tried it with both the plugins. It throws the same error. 
Could you elaborate on what do you mean by "without query"? Do you mean to just remove ```?1479654794267``` ? Or something else? 

BTW, I am not appending any query to the path. It is what Cordova camera plugin provides by default. 

May be I will check the path that is provided by camera and gallery and I will update

@salzig

**Comment by srameshr** [comment]
@salzig OMG!!! It was due to the query string. I removed query string and it worked! 👍 

If anyone comes here, please look at this. Here is the solution:

Here is the file path that is provided by Cordova when an image is chosen by gallery:

```
file:///storage/emulated/0/Android/data/com.app.ios/cache/IMG_20161122_124728.jpg?1083017394
```

You got to remove the query string ```?1083017394``` else, your app will crash.

```
var imagePath = file:///storage/emulated/0/Android/data/com.app.ios/cache/IMG_20161122_124728.jpg?1083017394;

if(imagePath.indexOf("?") > 0) {
  imagePath = imagePath.trim().split("?")[0];
}

```

And then provide this ```imagePath``` to the ```window.imageResizer.resizeImage``` function.

@JoschkaSchulz

**Comment by littldr** [comment]
@srameshr have you even tried this plugin? `info.protonet.imageresizer.ImageResizer` (They are similar, but not the same)

As I can see, this exception only happens in [RaananW/PhoneGap-Image-Resizer/.../ImageResizePlugin.java#L102](https://github.com/RaananW/PhoneGap-Image-Resizer/blob/master/src/Android/com/raananw/ImageResizer/ImageResizePlugin.java#L102) cause their are not using `FileHelper.getInputStreamFromUriString` provided here: `org.apache.cordova.camera.FileHelper` (with the same ['remove query'-hack used internally](https://github.com/apache/cordova-plugin-camera/blob/master/src/android/FileHelper.java#L175)). 

This helper is used in this repo (see: [ImageResizer.java#L95](https://github.com/protonet/cordova-plugin-image-resizer/blob/master/src/android/ImageResizer.java#L95). So your issue should not happen with this plugin.

**Comment by srameshr** [comment]
@LAndreas 

Then why are people who are using this plugin seems to be raising the same issue. As in this thread.

**Comment by littldr** [comment]
I'm not sure if this is the same issue like yours. Maybe @eliaweiss could provide a stracktrace?

**Comment by srameshr** [comment]
@LAandreas

Either way, the plugin fails when you try to upload an image from gallery.

**Comment by salzig** [comment]
@srameshr thats guessing, not knowing. Your problem happens cause of a different source code. 

would be cool if @eliaweiss or @twainyoung could provide a stacktrace.

**Comment by JoschkaSchulz** [comment]
Would like to see a Stack trace for that Project, then I can maybe invest some time to write a fix.

**Comment by srameshr** [comment]
@salzig True. PS: @eliaweiss @twainyoung
